import openai  

# Enter your OpenAI API key here  
openai.api_key = 'YOUR_API_KEY'  

def ask_gpt(question):  
    # Call the API to get a response from the GPT model  
    response = openai.ChatCompletion.create(  
        model='gpt-4',  
        messages=[  
            {'role': 'user', 'content': question}  
        ]  
    )  
    return response['choices'][0]['message']['content']  

# User input  
user_question = input("Ask the robot: ")  

# GPT response  
answer = ask_gpt(user_question)  
print("Robot's response:", answer)


# Code Explanation:
# Importing the Library:

# The openai library is imported, which is necessary for using the GPT models.
# Setting the API Key:

# Replace 'YOUR_API_KEY' with your OpenAI API key. (You need to have an OpenAI account and retrieve your API key from there).
# Function ask_gpt:

# This function sends the user's question to the GPT model and receives a response.
# It uses openai.ChatCompletion.create to initiate a conversation with the model.
# The user's question is sent in the messages parameter, and the response is extracted from content in the returned data.
# User Input:

# The program prompts the user to enter their question.
# Displaying the Response:

# The response generated by GPT is displayed on the console.
# How to Use:
# Save this code in a Python file (for example, robot.py).
# After installing the library and setting the API key, run the code.
# Enter your question when prompted, and receive the response.
